
### get all people 
GET http://localhost:4500/api/v1/people

###
POST http://localhost:4500/api/v1/people
Content-Type: 'application/json'

{
    "name": "Joshua", 
    "age": 12, 
    "height": "15m"
}